# This workflow checks the links in plaintext and HTML files
name: Check Links

on:
  # Uncomment the 'pull_request' line below to trigger the workflow in PR
  # pull_request:
  # Schedule runs on 12 noon every Sunday
  schedule:
    - cron: '0 12 * * 0'

jobs:
  check_links:
    name: Check Links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        path: repository

    - name: Checkout the website
      uses: actions/checkout@v3
      with:
        ref: gh-pages
        path: website

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.4.1
      with:
        # 429: Too many requests
        args: >
          --accept 429
          --exclude-mail
          --exclude https://seiscode.iris.washington.edu/
          --exclude http://www.kyoshin.bosai.go.jp/
          --exclude http://www.hinet.bosai.go.jp/
          --exclude https://www.fdsn.org/webservices/
          --exclude http://www.vnet.bosai.go.jp/
          --exclude http://www.fnet.bosai.go.jp/
          --exclude https://members.elsi.jp/~george/gh.html
          --exclude http://www.seisdmc.ac.cn/
          --exclude https://l2a.ucsd.edu/
          --exclude sac-help@lists.ds.iris.edu
          --verbose
          repository/README.md
          website/**/*.html
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Issue From File
      uses: peter-evans/create-issue-from-file@v3
      if: github.event_name != 'pull_request'
      with:
        title: Link Checker Report
        content-filepath: ./lychee/out.md
