#
# Build and deploy the documentation
#
name: Deploy

on:
  pull_request: # enable pull_request for testing
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip' # 自动缓存 pip 依赖

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build HTML documentation
        run: make build_html

      - name: Install Tectonic
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Tectonic packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
            ${{ runner.os }}-tectonic-

      - name: Build PDF documentation (Tectonic)
        run: make build_pdf

      - name: Move PDF to HTML directory
        run: |
          mkdir -p build/dirhtml
          cp build/latex/SAC_Docs.pdf build/dirhtml/SAC_Docs.pdf

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SAC_Docs_PDF
          path: build/latex/SAC_Docs.pdf
          retention-days: 5

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dirhtml
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
